/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paintbasico2d;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.color.ColorSpace;
import java.awt.color.ICC_ColorSpace;
import java.awt.color.ICC_Profile;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import static java.awt.image.AffineTransformOp.TYPE_BILINEAR;
import java.awt.image.BandCombineOp;
import java.awt.image.BufferedImage;
import static java.awt.image.BufferedImage.TYPE_INT_RGB;
import java.awt.image.ColorConvertOp;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.awt.image.LookupOp;
import java.awt.image.LookupTable;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author EDUARDO
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    BufferedImage img = null;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jSlider2 = new javax.swing.JSlider();
        jPanel11 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        oscurecer = new javax.swing.JButton();
        iluminar = new javax.swing.JButton();
        normal = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        rot90 = new javax.swing.JButton();
        rot180 = new javax.swing.JButton();
        rot270 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        aumentar = new javax.swing.JButton();
        disminuir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        barra = new javax.swing.JCheckBoxMenuItem();
        Imagen = new javax.swing.JMenu();
        ResacaleOp = new javax.swing.JMenuItem();
        ConvolveOp = new javax.swing.JMenuItem();
        AffineTransformOp = new javax.swing.JMenuItem();
        LookupOp = new javax.swing.JMenuItem();
        BandCombineOp = new javax.swing.JMenuItem();
        ColorConvertOp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/Lapiz.gif"))); // NOI18N
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
        });
        jToolBar2.add(jToggleButton4);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/Linea.gif"))); // NOI18N
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToolBar2.add(jToggleButton1);

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/Rectangulo.gif"))); // NOI18N
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });
        jToolBar2.add(jToggleButton2);

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/Ovalo.gif"))); // NOI18N
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });
        jToolBar2.add(jToggleButton3);

        jPanel2.add(jToolBar2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        escritorio.setPreferredSize(new java.awt.Dimension(1066, 300));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1066, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );

        jPanel1.add(escritorio, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 255, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grosor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 40, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jCheckBox1.setText("Rellenar");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jCheckBox2.setText("Editar");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(jCheckBox2)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Brillo"));
        jPanel10.setToolTipText("Brillo");
        jPanel10.setName(""); // NOI18N

        jSlider2.setPaintTicks(true);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jSlider2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSlider2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSlider2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));
        jPanel11.setToolTipText("");
        jPanel11.setName(""); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emborronamiento media", "Emborronamiento binomial", "Enfoque", "Relieve", "Detector de fronteras laplaciano" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraste"));

        oscurecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/oscurecer.png"))); // NOI18N
        oscurecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oscurecerActionPerformed(evt);
            }
        });

        iluminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iluminar.png"))); // NOI18N
        iluminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iluminarActionPerformed(evt);
            }
        });

        normal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/contraste.png"))); // NOI18N
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oscurecer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iluminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(normal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(oscurecer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iluminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(normal))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotación"));

        jSlider1.setMajorTickSpacing(90);
        jSlider1.setMaximum(360);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(180);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSlider1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSlider1FocusLost(evt);
            }
        });

        rot90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/rotacion90.png"))); // NOI18N
        rot90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rot90ActionPerformed(evt);
            }
        });

        rot180.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/rotacion180.png"))); // NOI18N
        rot180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rot180ActionPerformed(evt);
            }
        });

        rot270.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/rotacion270.png"))); // NOI18N
        rot270.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rot270ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(rot90, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rot180, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rot270, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rot180)
                    .addComponent(rot270, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rot90))
                .addContainerGap())
        );

        jSlider1.getAccessibleContext().setAccessibleName("");

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Escala"));

        aumentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/aumentar.png"))); // NOI18N
        aumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarActionPerformed(evt);
            }
        });

        disminuir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/disminuir.png"))); // NOI18N
        disminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disminuir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aumentar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disminuir)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.getAccessibleContext().setAccessibleDescription("");

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Barra de estado");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        Archivo.setText("Archivo");

        Nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/NuevoBoceto.GIF"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/Guardar.gif"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);

        jMenuBar1.add(Archivo);

        Edicion.setText("Edicion");

        barra.setSelected(true);
        barra.setText("Ver barra de estado");
        barra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barraStateChanged(evt);
            }
        });
        Edicion.add(barra);

        jMenuBar1.add(Edicion);

        Imagen.setText("Imagen");

        ResacaleOp.setText("ResacaleOp");
        ResacaleOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResacaleOpActionPerformed(evt);
            }
        });
        Imagen.add(ResacaleOp);

        ConvolveOp.setText("ConvolveOp");
        ConvolveOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvolveOpActionPerformed(evt);
            }
        });
        Imagen.add(ConvolveOp);

        AffineTransformOp.setText("AffineTransformOp");
        AffineTransformOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffineTransformOpActionPerformed(evt);
            }
        });
        Imagen.add(AffineTransformOp);

        LookupOp.setText("LookupOp");
        LookupOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LookupOpActionPerformed(evt);
            }
        });
        Imagen.add(LookupOp);

        BandCombineOp.setText("BandCombineOp");
        BandCombineOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandCombineOpActionPerformed(evt);
            }
        });
        Imagen.add(BandCombineOp);

        ColorConvertOp.setText("ColorConvertOp");
        ColorConvertOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorConvertOpActionPerformed(evt);
            }
        });
        Imagen.add(ColorConvertOp);

        jMenuBar1.add(Imagen);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
    }//GEN-LAST:event_NuevoActionPerformed

    private void barraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barraStateChanged
        // TODO add your handling code here:
        this.jLabel1.setVisible(this.barra.isSelected());
    }//GEN-LAST:event_barraStateChanged

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser(); 
        int resp = dlg.showOpenDialog(this); 
        if( resp == JFileChooser.APPROVE_OPTION) {  
             
            try {
                File f = dlg.getSelectedFile();
                BufferedImage img = ImageIO.read(f);
                VentanaInterna vi = new VentanaInterna();
                vi.getLienzo().setImage(img);
                this.escritorio.add(vi);
                vi.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
             
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna)escritorio.getSelectedFrame();
         BufferedImage img = vi.getLienzo().getImage();
        JFileChooser dlg = new JFileChooser(); 
        int resp = dlg.showSaveDialog(this); 
       if( resp == JFileChooser.APPROVE_OPTION) {     
            try {
                File f =  dlg.getSelectedFile();
                vi.getLienzo().pintarImagen(img);
                ImageIO.write(img,"jpg",f);
                
            } catch (IOException ex) {
                Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }                         
      }
    }//GEN-LAST:event_GuardarActionPerformed

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        // TODO add your handling code here:
       Lienzo.setForma(0);
       this.jLabel1.setText("Lápiz");
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        Lienzo.setForma(1);
        this.jLabel1.setText("Línea");
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        // TODO add your handling code here:
        Lienzo.setForma(2);
        this.jLabel1.setText("Rectángulo");
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        // TODO add your handling code here:
        Lienzo.setForma(3);
        this.jLabel1.setText("Elipse");
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Lienzo.setColor(Color.BLACK);
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Lienzo.setColor(Color.RED);
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Lienzo.setColor(Color.BLUE);
        repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Lienzo.setColor(Color.white);
        repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Lienzo.setColor(Color.YELLOW);
        repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Lienzo.setColor(Color.GREEN);
        repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        Lienzo.setRelleno(this.jCheckBox1.isSelected());
        repaint();
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        // TODO add your handling code here:
        Lienzo.setEditar(this.jCheckBox2.isSelected());
    }//GEN-LAST:event_jCheckBox2StateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        Lienzo.setStroke(new BasicStroke(((Integer)this.jSpinner1.getValue()).intValue()));
        repaint();
    }//GEN-LAST:event_jSpinner1StateChanged

    private void ResacaleOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResacaleOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
      if (vi != null) { 
        BufferedImage imgSource = vi.getLienzo().getImage(); 
        if(imgSource!=null){ 
            try{   
                 RescaleOp rop = new RescaleOp(1.0F, 100.0F, null); 
                 BufferedImage imgdest = rop.filter(imgSource, null); 
                 vi.getLienzo().setImage(imgdest); 
                 vi.getLienzo().repaint(); 
           } catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
            } 
        } 
      } 
    }//GEN-LAST:event_ResacaleOpActionPerformed

    private void ConvolveOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvolveOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) { 
            BufferedImage imgSource = vi.getLienzo().getImage(); 
            if(imgSource!=null){
              try{ 
                float filtromedia [] = { 0.1f, 0.1f, 0.1f, 
                                         0.1f, 0.2f, 0.1f , 
                                         0.1f, 0.1f, 0.1f };
                Kernel k = new Kernel(3,3,filtromedia);
                ConvolveOp cop = new ConvolveOp(k);
                BufferedImage imgOut = cop.filter(imgSource, null);
                vi.getLienzo().setImage(imgOut); 
                vi.getLienzo().repaint();
             }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
               } 
            }
        }
                
    }//GEN-LAST:event_ConvolveOpActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        
      if (vi != null) {
          BufferedImage imgSource = vi.getLienzo().getImage(); 
        
            if(imgSource != null){ 
            try{
                 float brillo = jSlider2.getValue();
                 RescaleOp rop = new RescaleOp(1.0F,brillo, null); 
                 BufferedImage imgdest = rop.filter(img, null); 
                 vi.getLienzo().setImage(imgdest); 
                 vi.getLienzo().repaint(); 
           } catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
            }
          }
         
     } 
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSlider2FocusLost
        // TODO add your handling code here:
        img = null;
    }//GEN-LAST:event_jSlider2FocusLost

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        //int filtro = 0;
        Kernel k=null;
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        
     if(vi != null){
          BufferedImage imgSource = vi.getLienzo().getImage();
      if(imgSource != null){  
       try{
        switch(jComboBox2.getSelectedIndex())
        {
            case 0:
                k = KernelProducer.createKernel(KernelProducer.TYPE_MEDIA_3x3);         
                break;
            case 1:
                k = KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);              
                break;
            case 2:
                k = KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3);     
                break;
            case 3: 
                k = KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3);       
                break;
            case 4:
                k = KernelProducer.createKernel(KernelProducer.TYPE_LAPLACIANA_3x3);              
                break;
        }
                ConvolveOp cop = new ConvolveOp(k);
                BufferedImage imgOut = cop.filter(imgSource, null);
                vi.getLienzo().setImage(imgOut); 
                vi.getLienzo().repaint();
       }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
            } 
       
      }
    }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void AffineTransformOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffineTransformOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
         BufferedImage imgSource = vi.getLienzo().getImage();
        AffineTransform //at = AffineTransform.getScaleInstance(1.25,1.25);
        //at = AffineTransform.getRotateInstance(Math.toRadians(180.0),imgSource.getWidth()/2,imgSource.getHeight()/2); 
        at = AffineTransform.getShearInstance(0.5,0.0); 
        //at = AffineTransform.getTranslateInstance(20.0,20.0); 
      if(vi != null){
          if(imgSource != null){ 
        try{
             AffineTransformOp atop = new AffineTransformOp(at, TYPE_BILINEAR);
             BufferedImage imgOut = atop.filter( imgSource, null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }    
    }//GEN-LAST:event_AffineTransformOpActionPerformed

    BufferedImage convertImageType(BufferedImage img, int type){ 
       if(img==null) return null; 
       BufferedImage imgOut = new BufferedImage(img.getWidth(), 
  img.getHeight(), type); 
       Graphics2D g2d = imgOut.createGraphics(); 
       g2d.drawImage(img,0,0,null); 
       return imgOut; 
 } 
    private void LookupOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LookupOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
    if(vi != null){
        BufferedImage imgSource = vi.getLienzo().getImage();
        BufferedImage imgSource1=convertImageType(imgSource, TYPE_INT_RGB);
      if(imgSource != null){ 
        try{
            LookupTable it = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_NEGATIVE);
            LookupOp lop = new LookupOp(it,null);
            BufferedImage imgOut = lop.filter(imgSource1,null);
            vi.getLienzo().setImage(imgOut); 
            vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }       
    }//GEN-LAST:event_LookupOpActionPerformed

    private void BandCombineOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandCombineOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        WritableRaster  rasterdest; 
           
    if(vi != null){
        BufferedImage imgSource = vi.getLienzo().getImage();
      if(imgSource != null){ 
        try{
            float [][] m = {{1.0F,0.0F,0.0F},{0.0F,0.0F,1.0F},{0.0F,1.0F,0.0F}}; 
            BandCombineOp bcop = new BandCombineOp( m , null );
            rasterdest = bcop.filter(imgSource.getRaster(),null);
            BufferedImage imgOut = new BufferedImage(imgSource.getColorModel(),rasterdest,false,null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }       
    }//GEN-LAST:event_BandCombineOpActionPerformed

    private void ColorConvertOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorConvertOpActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        ICC_Profile ip;
                
        if(vi != null){
        BufferedImage imgSource = vi.getLienzo().getImage();
      if(imgSource != null){ 
        try{
            ip = ICC_Profile.getInstance(ColorSpace.CS_GRAY); 
            ColorSpace cs = new ICC_ColorSpace(ip); 
            ColorConvertOp ccop = new ColorConvertOp(cs,null); 
            BufferedImage imgOut = ccop.filter(imgSource,null);            
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }       
    }//GEN-LAST:event_ColorConvertOpActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:    
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
    if(vi != null){
        BufferedImage imgSource = vi.getLienzo().getImage();
        BufferedImage imgSource1=convertImageType(imgSource, TYPE_INT_RGB);
      if(imgSource != null){ 
        try{
            LookupTable it = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_SFUNCION);
            LookupOp lop = new LookupOp(it,null);
            BufferedImage imgOut = lop.filter(imgSource1,null);
            vi.getLienzo().setImage(imgOut); 
            vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }      
    }//GEN-LAST:event_normalActionPerformed

    private void iluminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iluminarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
    if(vi != null){
        BufferedImage imgSource = vi.getLienzo().getImage();
        BufferedImage imgSource1=convertImageType(imgSource, TYPE_INT_RGB);
      if(imgSource != null){ 
        try{
            LookupTable it = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_LOGARITHM);
            LookupOp lop = new LookupOp(it,null);
            BufferedImage imgOut = lop.filter(imgSource1,null);
            vi.getLienzo().setImage(imgOut); 
            vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      } 
    }//GEN-LAST:event_iluminarActionPerformed

    private void oscurecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oscurecerActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
    if(vi != null){
        BufferedImage imgSource = vi.getLienzo().getImage();
        BufferedImage imgSource1=convertImageType(imgSource, TYPE_INT_RGB);
      if(imgSource != null){ 
        try{
            LookupTable it = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_POWER);
            LookupOp lop = new LookupOp(it,null);
            BufferedImage imgOut = lop.filter(imgSource1,null);
            vi.getLienzo().setImage(imgOut); 
            vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      } 
    }//GEN-LAST:event_oscurecerActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        BufferedImage imgSource = vi.getLienzo().getImage();
        double grados = jSlider1.getValue();
        double r = Math.toRadians(grados);
        //Point c = new Point(vi.getLienzo().getWidth()/2, vi.getLienzo().getHeight()/2);
             
        if(vi != null){
          
          if(imgSource != null){ 
        try{
             AffineTransform at = AffineTransform.getRotateInstance(r,img.getWidth()/2,img.getHeight()/2);
             AffineTransformOp atop = new AffineTransformOp(at, TYPE_BILINEAR);
             BufferedImage imgOut = atop.filter( img, null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }            
    }//GEN-LAST:event_jSlider1StateChanged

    private void rot90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rot90ActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        BufferedImage imgSource = vi.getLienzo().getImage();
        double r = Math.toRadians(90); 
        Point c = new Point(imgSource.getWidth()/2, imgSource.getHeight()/2); 
        AffineTransform at = AffineTransform.getRotateInstance(r,c.x,c.y);
        
        if(vi != null){
          if(imgSource != null){ 
        try{
             AffineTransformOp atop = new AffineTransformOp(at, TYPE_BILINEAR);
             BufferedImage imgOut = atop.filter( imgSource, null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }      
    }//GEN-LAST:event_rot90ActionPerformed

    private void rot180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rot180ActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        BufferedImage imgSource = vi.getLienzo().getImage();
        double r = Math.toRadians(180); 
        Point c = new Point(imgSource.getWidth()/2, imgSource.getHeight()/2); 
        AffineTransform at = AffineTransform.getRotateInstance(r,c.x,c.y);
        
        if(vi != null){
          if(imgSource != null){ 
        try{
             AffineTransformOp atop = new AffineTransformOp(at, TYPE_BILINEAR);
             BufferedImage imgOut = atop.filter( imgSource, null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }             
    }//GEN-LAST:event_rot180ActionPerformed

    private void rot270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rot270ActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        BufferedImage imgSource = vi.getLienzo().getImage();
        double r = Math.toRadians(270); 
        Point c = new Point(imgSource.getWidth()/2, imgSource.getHeight()/2); 
        AffineTransform at = AffineTransform.getRotateInstance(r,c.x,c.y);
        
        if(vi != null){
          if(imgSource != null){ 
        try{
             AffineTransformOp atop = new AffineTransformOp(at, TYPE_BILINEAR);
             BufferedImage imgOut = atop.filter( imgSource, null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }      
    }//GEN-LAST:event_rot270ActionPerformed

    private void aumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        BufferedImage imgSource = vi.getLienzo().getImage();  
        AffineTransform at = AffineTransform.getScaleInstance(1.25,1.25);
        
        if(vi != null){
          if(imgSource != null){ 
        try{
             AffineTransformOp atop = new AffineTransformOp(at, TYPE_BILINEAR);
             BufferedImage imgOut = atop.filter( imgSource, null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }        
    }//GEN-LAST:event_aumentarActionPerformed

    private void disminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        BufferedImage imgSource = vi.getLienzo().getImage();
        AffineTransform at = AffineTransform.getScaleInstance(0.75,0.75);      
        if(vi != null){
          if(imgSource != null){ 
        try{
             AffineTransformOp atop = new AffineTransformOp(at, TYPE_BILINEAR);
             BufferedImage imgOut = atop.filter( imgSource, null);  
             vi.getLienzo().setImage(imgOut); 
             vi.getLienzo().repaint();
        }catch(IllegalArgumentException e){ 
                    System.err.println(e.getLocalizedMessage()); 
        }
       }
      }        
    }//GEN-LAST:event_disminuirActionPerformed

    private void jSlider1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSlider1FocusLost
        // TODO add your handling code here:
        img=null;
    }//GEN-LAST:event_jSlider1FocusLost

    private void jSlider1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSlider1FocusGained
        // TODO add your handling code here:
         VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
          if(vi != null){
              img = vi.getLienzo().getImage();
          }         
    }//GEN-LAST:event_jSlider1FocusGained

    private void jSlider2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSlider2FocusGained
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
          if(vi != null){
              img = vi.getLienzo().getImage();
          }
    }//GEN-LAST:event_jSlider2FocusGained


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenuItem AffineTransformOp;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem BandCombineOp;
    private javax.swing.JMenuItem ColorConvertOp;
    private javax.swing.JMenuItem ConvolveOp;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenu Imagen;
    private javax.swing.JMenuItem LookupOp;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenuItem ResacaleOp;
    private javax.swing.JButton aumentar;
    private javax.swing.JCheckBoxMenuItem barra;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton disminuir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton iluminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton normal;
    private javax.swing.JButton oscurecer;
    private javax.swing.JButton rot180;
    private javax.swing.JButton rot270;
    private javax.swing.JButton rot90;
    // End of variables declaration//GEN-END:variables
}
